c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]

tgt_platform:
  - linux-64
  - linux-aarch64
  - linux-ppc64le
cross_target_platform:
  -
    - linux-64
    - linux-64
    - linux-64
  -
    - linux-aarch64
    - linux-aarch64
    - linux-aarch64
  -
    - linux-ppc64le
    - linux-ppc64le
    - linux-ppc64le
cross_target_impl_platform:
  -
    - linux-64
    - linux-aarch64
    - linux-ppc64le
  -
    - linux-64
    - linux-aarch64
    - linux-ppc64le
  -
    - linux-64
    - linux-aarch64
    - linux-ppc64le

zip_keys:
  -
    - tgt_platform
    - cross_target_platform
    - cross_target_impl_platform
