c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
arm_variant_type:
  - sbsa

cross_target_platform:
  - linux-64
  - linux-aarch64
  - linux-ppc64le
