c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]

arm_variant_type:          # [aarch64]
  - sbsa                   # [aarch64]

glibc_version:             # [linux]
  - 2.17                   # [linux]
