c_compiler_version:        # [linux]
  - 12                     # [linux]
cxx_compiler_version:      # [linux]
  - 12                     # [linux]
arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]

cross_target_platform:
  - linux-64
  - linux-aarch64
  - linux-ppc64le
cross_target_name:
  - x86_64-linux
  - sbsa-linux
  - ppc64le-linux

zip_keys:
  -
    - cross_target_platform
    - cross_target_name
